export const accountCopy = {
  ko: {
    eyebrow: "ACCOUNT / PERSONAL ARCHIVE", title: "계정 설정", titleAccent: "", intro: "이름과 로그인 정보를 최신 상태로 관리하세요. 변경한 정보는 이 계정을 사용하는 모든 곳에 반영됩니다.", profileTitle: "기본 정보", profileDescription: "서비스에서 사용할 이름입니다.", avatarTitle: "아바타", avatarDescription: "좋아하는 아티스트의 이미지로 계정을 표현하세요.", defaultAvatar: "기본 아바타", saveAvatar: "아바타 저장", avatarSaved: "아바타를 저장했습니다.", noAvatars: "선택할 수 있는 아바타가 아직 없습니다.", name: "이름", saveName: "이름 저장", nameSaved: "이름을 저장했습니다.", emailTitle: "이메일", emailDescription: "로그인과 계정 알림에 사용합니다.", email: "이메일 주소", emailHint: "새 주소로 전송된 인증 링크를 확인해야 변경이 완료됩니다.", saveEmail: "이메일 변경", sameEmail: "현재 이메일과 같은 주소입니다.", emailSent: "새 이메일로 인증 링크를 보냈습니다.", passwordTitle: "비밀번호", passwordDescription: "안전한 비밀번호로 주기적으로 변경하세요.", currentPassword: "현재 비밀번호", currentPasswordHint: "현재 비밀번호를 먼저 입력하세요. 입력을 마치면 자동으로 확인합니다.", currentPasswordChecking: "현재 비밀번호를 확인하는 중입니다.", currentPasswordVerified: "현재 비밀번호를 확인했습니다.", currentPasswordRequired: "현재 비밀번호 확인을 먼저 완료하세요.", newPassword: "새 비밀번호", confirmPassword: "새 비밀번호 확인", passwordHint: "현재 비밀번호를 확인한 뒤 12자 이상의 새 비밀번호로 변경합니다.", changePassword: "비밀번호 변경", passwordLength: "비밀번호는 12자 이상이어야 합니다.", passwordMismatch: "비밀번호가 일치하지 않습니다.", currentPasswordInvalid: "현재 비밀번호가 올바르지 않습니다.", captchaFailed: "보안 인증에 실패했습니다. 잠시 후 다시 시도해 주세요.", passwordSaved: "비밀번호를 변경했습니다.", sessionTitle: "세션", sessionDescription: "이 기기에서 계정 사용을 마칩니다.", signOut: "로그아웃", saving: "저장 중", loadError: "계정 정보를 불러오지 못했습니다.", genericError: "변경 내용을 저장하지 못했습니다.", loading: "계정 정보를 불러오는 중",
  },
  en: {
    eyebrow: "ACCOUNT / PERSONAL ARCHIVE", title: "Account settings", titleAccent: "", intro: "Keep your name and sign-in details current. Updates apply everywhere you use this account.", profileTitle: "Profile", profileDescription: "The name shown across the service.", avatarTitle: "Avatar", avatarDescription: "Choose an account image from your favorite artist.", defaultAvatar: "Default avatar", saveAvatar: "SAVE AVATAR", avatarSaved: "Your avatar has been saved.", noAvatars: "No artist avatars are available yet.", name: "NAME", saveName: "SAVE NAME", nameSaved: "Your name has been saved.", emailTitle: "Email", emailDescription: "Used for sign-in and account messages.", email: "EMAIL ADDRESS", emailHint: "Open the verification link sent to your new address to finish the change.", saveEmail: "CHANGE EMAIL", sameEmail: "This is already your current email.", emailSent: "A verification link was sent to your new email.", passwordTitle: "Password", passwordDescription: "Refresh it regularly to keep your account secure.", currentPassword: "CURRENT PASSWORD", currentPasswordHint: "Enter your current password first. It will be checked when you finish typing.", currentPasswordChecking: "Checking your current password.", currentPasswordVerified: "Your current password has been verified.", currentPasswordRequired: "Verify your current password first.", newPassword: "NEW PASSWORD", confirmPassword: "CONFIRM NEW PASSWORD", passwordHint: "Confirm your current password, then use at least 12 characters for the new password.", changePassword: "CHANGE PASSWORD", passwordLength: "Password must be at least 12 characters.", passwordMismatch: "Passwords do not match.", currentPasswordInvalid: "The current password is incorrect.", captchaFailed: "Security verification failed. Please try again shortly.", passwordSaved: "Your password has been changed.", sessionTitle: "Session", sessionDescription: "Finish using this account on this device.", signOut: "SIGN OUT", saving: "SAVING", loadError: "We couldn't load your account.", genericError: "We couldn't save your changes.", loading: "Loading your account",
  },
  ja: {
    eyebrow: "ACCOUNT / PERSONAL ARCHIVE", title: "アカウント設定", titleAccent: "", intro: "名前とログイン情報を最新の状態に保ちます。変更内容は、このアカウントを使うすべての場所に反映されます。", profileTitle: "基本情報", profileDescription: "サービスに表示される名前です。", avatarTitle: "アバター", avatarDescription: "好きなアーティストの画像をアカウントに設定できます。", defaultAvatar: "基本アバター", saveAvatar: "アバターを保存", avatarSaved: "アバターを保存しました。", noAvatars: "選択できるアバターはまだありません。", name: "名前", saveName: "名前を保存", nameSaved: "名前を保存しました。", emailTitle: "メール", emailDescription: "ログインとアカウント通知に使用します。", email: "メールアドレス", emailHint: "新しいアドレスに届く認証リンクを開くと変更が完了します。", saveEmail: "メールを変更", sameEmail: "現在のメールアドレスと同じです。", emailSent: "新しいメールアドレスに認証リンクを送りました。", passwordTitle: "パスワード", passwordDescription: "安全のため定期的に更新してください。", currentPassword: "現在のパスワード", currentPasswordHint: "最初に現在のパスワードを入力してください。入力後に自動で確認します。", currentPasswordChecking: "現在のパスワードを確認しています。", currentPasswordVerified: "現在のパスワードを確認しました。", currentPasswordRequired: "最初に現在のパスワードを確認してください。", newPassword: "新しいパスワード", confirmPassword: "新しいパスワード（確認）", passwordHint: "現在のパスワードを確認し、12文字以上の新しいパスワードを入力してください。", changePassword: "パスワードを変更", passwordLength: "パスワードは12文字以上必要です。", passwordMismatch: "パスワードが一致しません。", currentPasswordInvalid: "現在のパスワードが正しくありません。", captchaFailed: "セキュリティ認証に失敗しました。しばらくしてからもう一度お試しください。", passwordSaved: "パスワードを変更しました。", sessionTitle: "セッション", sessionDescription: "この端末でのアカウント利用を終了します。", signOut: "ログアウト", saving: "保存中", loadError: "アカウント情報を読み込めませんでした。", genericError: "変更を保存できませんでした。", loading: "アカウント情報を読み込み中",
  },
} as const;
