import Image from "next/image";
import Link from "next/link";
import { LogIn, Moon, Sun } from "lucide-react";
import LanguageSwitcher from "./LanguageSwitcher";
import type { ArtistNavigationItem, NavTranslations } from "./navbar-types";
import styles from "@/styles/(public)/components/layout/Navbar.module.css";

type Props = { artists: ArtistNavigationItem[]; pathname: string; isAdmin: boolean; isLoggedIn: boolean; authReady: boolean; accountAvatarUrl: string | null; accountInitial: string; accountName: string; isDark: boolean; t: NavTranslations; expandedArtist: string | null; setExpandedArtist: (slug: string | null) => void; onToggleTheme: () => void };
const artistLinks = (slug: string) => [{ href: `/${slug}/artist`, label: "ABOUT" }, { href: `/${slug}/discography`, label: "DISCOGRAPHY" }, { href: `/${slug}/schedule`, label: "SCHEDULE" }, { href: `/${slug}/notice`, label: "NOTICE" }];

export default function DesktopNav({ artists, pathname, isAdmin, isLoggedIn, authReady, accountAvatarUrl, accountInitial, accountName, isDark, t, expandedArtist, setExpandedArtist, onToggleTheme }: Props) {
  const linkClass = (path: string) => `${styles.navLink} ${pathname === path ? styles.navLinkActive : ""}`;
  return <div className={`hidden w-full items-center xl:flex ${authReady ? "" : styles.authLoading}`}>
    <Link href="/" className="relative block h-10 w-40 shrink-0 transition-opacity duration-base hover:opacity-75"><Image src="/images/logo.png" alt="THE MUZE Logo" fill sizes="160px" className={`${styles.logoImage} ${isDark ? styles.logoDark : ""}`} priority /></Link>
    <nav className="ml-10 flex items-center gap-8"><Link href="/about" className={linkClass("/about")}>{t.nav.about}</Link>{(artists || []).map((artist) => <div key={artist.id} className="relative" onMouseEnter={() => setExpandedArtist(artist.slug)} onMouseLeave={() => setExpandedArtist(null)}><button type="button" onFocus={() => setExpandedArtist(artist.slug)} className={`${styles.navLink} ${expandedArtist === artist.slug || pathname.startsWith(`/${artist.slug}/`) ? styles.navLinkActive : ""}`} aria-expanded={expandedArtist === artist.slug}><span className={styles.artistLogoBadge}>{artist.logo_url ? <Image src={artist.logo_url} alt="" width={16} height={16} unoptimized={/\.svg(?:$|\?)/i.test(artist.logo_url)} className={/\.svg(?:$|\?)/i.test(artist.logo_url) ? "is-theme-svg" : undefined} /> : <i />}</span>{artist.name}</button><div className={`absolute left-1/2 top-full z-50 w-44 -translate-x-1/2 pt-2 transition-all duration-base ${expandedArtist === artist.slug ? "visible translate-y-0 opacity-100" : "invisible -translate-y-1 opacity-0"}`}><div className={styles.dropdownCard}>{artistLinks(artist.slug).map(({ href, label }) => <Link key={href} href={href} className={`${styles.dropdownItem} ${pathname === href ? styles.dropdownItemActive : ""}`}>{label}</Link>)}</div></div></div>)}<Link href="/audition" className={linkClass("/audition")}>{t.nav.audition}</Link><Link href="/notice" className={linkClass("/notice")}>{t.nav.notice}</Link><Link href="/protect" className={linkClass("/protect")}>PROTECT</Link><Link href="/contact" className={linkClass("/contact")}>CONTACT</Link>{isAdmin && <Link href="/admin" className={linkClass("/admin")}>ADMIN</Link>}</nav>
    <div className={`${styles.utilityGroup} ml-auto`}><LanguageSwitcher /><button type="button" onClick={onToggleTheme} aria-label={isDark ? t.common.lightMode : t.common.darkMode} className={styles.themeToggleBtn}><div className={`${styles.themeToggleThumb} ${isDark ? styles.themeToggleThumbDark : ""}`}>{isDark ? <Moon size={13} /> : <Sun size={13} />}</div><div className={styles.themeToggleIcons}><Sun size={12} className={!isDark ? "opacity-0" : "opacity-60 transition-opacity duration-slow"} /><Moon size={12} className={isDark ? "opacity-0" : "opacity-60 transition-opacity duration-slow"} /></div></button><Link href={isLoggedIn ? "/account" : "/login"} className={`${styles.accountBtn} ${isLoggedIn ? styles.accountBtnLoggedIn : styles.accountBtnLoggedOut}`} title={isLoggedIn ? accountName : undefined}>{isLoggedIn ? <><span className={styles.accountAvatar}>{accountAvatarUrl ? <Image src={accountAvatarUrl} alt="" width={22} height={22} sizes="22px" /> : <b aria-hidden="true">{accountInitial}</b>}</span><span className={styles.accountName}>{accountName}</span></> : <><LogIn className={styles.accountBtnIcon} /><span>LOGIN</span></>}</Link></div>
  </div>;
}
