import Image from "next/image";
import Link from "next/link";
import { LuLogIn, LuMoon, LuSun, LuUser } from "react-icons/lu";
import LanguageSwitcher from "./LanguageSwitcher";
import type { ArtistNavigationItem, NavTranslations } from "./navbar-types";
import styles from "@/styles/(public)/components/layout/Navbar.module.css";

type Props = { artists: ArtistNavigationItem[]; pathname: string; isAdmin: boolean; isLoggedIn: boolean; isDark: boolean; t: NavTranslations; expandedArtist: string | null; setExpandedArtist: (slug: string | null) => void; onToggleTheme: () => void };
const artistLinks = (slug: string) => [{ href: `/${slug}/artist`, label: "ABOUT" }, { href: `/${slug}/discography`, label: "DISCOGRAPHY" }, { href: `/${slug}/schedule`, label: "SCHEDULE" }, { href: `/${slug}/notice`, label: "NOTICE" }];

export default function DesktopNav({ artists, pathname, isAdmin, isLoggedIn, isDark, t, expandedArtist, setExpandedArtist, onToggleTheme }: Props) {
  const linkClass = (path: string) => `${styles.navLink} ${pathname === path ? styles.navLinkActive : ""}`;
  return <div className="hidden w-full items-center md:flex">
    <Link href="/" className="relative block h-10 w-40 shrink-0 transition-opacity duration-base hover:opacity-75"><Image src="/images/logo.png" alt="THE MUZE Logo" fill sizes="160px" className={`${styles.logoImage} ${isDark ? styles.logoDark : ""}`} priority /></Link>
    <nav className="ml-10 flex items-center gap-8"><Link href="/about" className={linkClass("/about")}>{t.nav.about}</Link>{(artists || []).map((artist) => <div key={artist.id} className="relative" onMouseEnter={() => setExpandedArtist(artist.slug)} onMouseLeave={() => setExpandedArtist(null)}><button type="button" onFocus={() => setExpandedArtist(artist.slug)} className={`${styles.navLink} ${expandedArtist === artist.slug || pathname.startsWith(`/${artist.slug}/`) ? styles.navLinkActive : ""}`} aria-expanded={expandedArtist === artist.slug}><span className={styles.artistLogoBadge}>{artist.logo_url ? <Image src={artist.logo_url} alt="" width={16} height={16} unoptimized={/\.svg(?:$|\?)/i.test(artist.logo_url)} className={/\.svg(?:$|\?)/i.test(artist.logo_url) ? "is-theme-svg" : undefined} /> : <i />}</span>{artist.name}</button><div className={`absolute left-1/2 top-full z-50 w-44 -translate-x-1/2 pt-2 transition-all duration-base ${expandedArtist === artist.slug ? "visible translate-y-0 opacity-100" : "invisible -translate-y-1 opacity-0"}`}><div className={styles.dropdownCard}>{artistLinks(artist.slug).map(({ href, label }) => <Link key={href} href={href} className={`${styles.dropdownItem} ${pathname === href ? styles.dropdownItemActive : ""}`}>{label}</Link>)}</div></div></div>)}<Link href="/notice" className={linkClass("/notice")}>{t.nav.notice}</Link><Link href="/protect" className={linkClass("/protect")}>PROTECT</Link>{isAdmin && <Link href="/admin" className={linkClass("/admin")}>ADMIN</Link>}</nav>
    <div className={`${styles.utilityGroup} ml-auto`}><LanguageSwitcher /><button type="button" onClick={onToggleTheme} aria-label={isDark ? "Switch to light mode" : "Switch to dark mode"} className={styles.themeToggleBtn}><div className={`${styles.themeToggleThumb} ${isDark ? styles.themeToggleThumbDark : ""}`}>{isDark ? <LuMoon size={13} /> : <LuSun size={13} />}</div><div className={styles.themeToggleIcons}><LuSun size={12} className={!isDark ? "opacity-0" : "opacity-60 transition-opacity duration-slow"} /><LuMoon size={12} className={isDark ? "opacity-0" : "opacity-60 transition-opacity duration-slow"} /></div></button><Link href={isLoggedIn ? "/account" : "/login"} className={`${styles.accountBtn} ${isLoggedIn ? styles.accountBtnLoggedIn : styles.accountBtnLoggedOut}`}>{isLoggedIn ? <><LuUser className={styles.accountBtnIcon} /><span>ACCOUNT</span></> : <><LuLogIn className={styles.accountBtnIcon} /><span>LOGIN</span></>}</Link></div>
  </div>;
}
