import type { Locale } from "@/core/i18n/localized";

type AuditionMessages = {
  description: string; menu: string; mine: string; apply: string; account: string; closeError: string; loadError: string;
  total: (count: number) => string; emptyTitle: string; emptyDescription: string; campaignFallback: string; applicationFallback: string; receipt: string; edit: string;
  campaign: string; selectCampaign: string; noCampaign: string; noCampaignDescription: string; deadline: (date: string) => string;
  status: Record<"pending" | "reviewing" | "accepted" | "rejected", string>;
  required: (label: string) => string; invalidEmail: (label: string) => string; consent: (label: string) => string; tooLong: (label: string, max: number) => string; fileTooLarge: (label: string) => string;
  submitFailed: string; saved: string; updated: string; viewMine: string; review: string; reviewNew: string; reviewUpdate: string; revise: string; saving: string; saveUpdate: string; finalSubmit: string;
  select: string; replaceFile: string; chooseFile: string; maxFile: (max: number) => string; existingFile: string; removeFile: string; reviewChanges: string; reviewSubmission: string;
  errors: Record<string, string>;
};

export const auditionMessages: Record<Locale, AuditionMessages> = {
  ko: {
    description: "진행 중인 오디션에 지원하고 접수 상태를 확인하세요.", menu: "오디션 메뉴", mine: "내 지원", apply: "지원하기", account: "로그인 계정으로 안전하게 관리됩니다.", closeError: "오류 메시지 닫기", loadError: "오디션 정보를 불러오지 못했습니다.",
    total: (count) => `총 ${count}건`, emptyTitle: "아직 제출한 지원서가 없습니다.", emptyDescription: "진행 중인 캠페인을 선택해 지원해 보세요.", campaignFallback: "오디션", applicationFallback: "지원서", receipt: "접수번호", edit: "수정", campaign: "오디션 캠페인", selectCampaign: "캠페인을 선택하세요", noCampaign: "현재 지원 가능한 오디션이 없습니다.", noCampaignDescription: "새 모집이 시작되면 이곳에서 안내합니다.", deadline: (date) => `${date} 마감`,
    status: { pending: "접수", reviewing: "심사 중", accepted: "합격", rejected: "불합격" }, required: (label) => `${label} 항목을 확인해 주세요.`, invalidEmail: (label) => `${label} 형식을 확인해 주세요.`, consent: (label) => `${label} 동의가 필요합니다.`, tooLong: (label, max) => `${label} 항목은 ${max}자까지 입력할 수 있습니다.`, fileTooLarge: (label) => `${label} 파일 크기를 확인해 주세요.`,
    submitFailed: "제출하지 못했습니다. 입력 내용을 확인해 주세요.", saved: "지원서가 접수되었습니다.", updated: "지원서가 수정되었습니다.", viewMine: "내 지원 확인", review: "제출 전 확인", reviewNew: "아래 내용으로 지원서를 제출합니다.", reviewUpdate: "수정한 내용으로 지원서를 저장합니다.", revise: "수정하기", saving: "저장 중…", saveUpdate: "수정 저장", finalSubmit: "최종 제출", select: "선택하세요", replaceFile: "다른 파일로 교체", chooseFile: "파일 선택", maxFile: (max) => `최대 ${max}MB`, existingFile: "기존 파일", removeFile: "파일 제거", reviewChanges: "수정 내용 검토", reviewSubmission: "제출 내용 검토",
    errors: { REQUIRED_FIELD_MISSING: "필수 항목을 모두 입력해 주세요.", VALID_EMAIL_REQUIRED: "올바른 이메일 주소를 입력해 주세요.", CONSENT_REQUIRED: "필수 동의 항목을 확인해 주세요.", INVALID_OPTION: "선택 항목을 다시 확인해 주세요.", INVALID_DATE: "날짜를 다시 확인해 주세요.", ANSWER_TOO_LONG: "입력 가능한 글자 수를 초과한 항목이 있습니다.", INVALID_FILE_TYPE: "허용되지 않는 파일 형식입니다.", FILE_TOO_LARGE: "첨부 파일의 용량을 확인해 주세요.", CAMPAIGN_CLOSED: "지원 기간이 종료되었습니다.", ALREADY_SUBMITTED: "이 캠페인에 제출한 지원서가 이미 있습니다.", RATE_LIMITED: "오늘 제출 가능한 횟수를 초과했습니다.", UNAUTHORIZED: "로그인 후 지원해 주세요.", SUBMISSION_NOT_FOUND: "수정할 지원서를 찾지 못했습니다.", SERVICE_UNAVAILABLE: "제출 서비스를 잠시 사용할 수 없습니다.", SUBMISSION_FAILED: "지원서를 저장하지 못했습니다. 잠시 후 다시 시도해 주세요." },
  },
  en: {
    description: "Apply to an open audition and check your application status.", menu: "Audition menu", mine: "My applications", apply: "Apply", account: "Applications are securely linked to your account.", closeError: "Close error message", loadError: "We couldn't load the audition information.",
    total: (count) => `${count} total`, emptyTitle: "You haven't submitted an application yet.", emptyDescription: "Choose an open campaign to get started.", campaignFallback: "Audition", applicationFallback: "Application", receipt: "Receipt", edit: "Edit", campaign: "Audition campaign", selectCampaign: "Select a campaign", noCampaign: "There are no auditions open for applications.", noCampaignDescription: "New campaigns will be announced here.", deadline: (date) => `Closes ${date}`,
    status: { pending: "Received", reviewing: "Under review", accepted: "Accepted", rejected: "Not selected" }, required: (label) => `Please complete ${label}.`, invalidEmail: (label) => `Check the format of ${label}.`, consent: (label) => `You must agree to ${label}.`, tooLong: (label, max) => `${label} can contain up to ${max} characters.`, fileTooLarge: (label) => `Check the file size for ${label}.`,
    submitFailed: "We couldn't submit the application. Check your entries.", saved: "Your application has been submitted.", updated: "Your application has been updated.", viewMine: "View my applications", review: "Review before submitting", reviewNew: "Your application will be submitted with the details below.", reviewUpdate: "Your application will be saved with the changes below.", revise: "Go back", saving: "Saving…", saveUpdate: "Save changes", finalSubmit: "Submit application", select: "Select", replaceFile: "Replace file", chooseFile: "Choose file", maxFile: (max) => `Up to ${max} MB`, existingFile: "Existing file", removeFile: "Remove file", reviewChanges: "Review changes", reviewSubmission: "Review application",
    errors: { REQUIRED_FIELD_MISSING: "Complete all required fields.", VALID_EMAIL_REQUIRED: "Enter a valid email address.", CONSENT_REQUIRED: "Review the required consent fields.", INVALID_OPTION: "Check the selected option.", INVALID_DATE: "Check the date.", ANSWER_TOO_LONG: "One or more answers exceed the character limit.", INVALID_FILE_TYPE: "This file type is not allowed.", FILE_TOO_LARGE: "Check the attached file size.", CAMPAIGN_CLOSED: "The application period has ended.", ALREADY_SUBMITTED: "You already have an application for this campaign.", RATE_LIMITED: "You have reached today's submission limit.", UNAUTHORIZED: "Sign in to apply.", SUBMISSION_NOT_FOUND: "We couldn't find the application to update.", SERVICE_UNAVAILABLE: "The submission service is temporarily unavailable.", SUBMISSION_FAILED: "We couldn't save the application. Please try again shortly." },
  },
  ja: {
    description: "開催中のオーディションに応募し、受付状況を確認できます。", menu: "オーディションメニュー", mine: "応募履歴", apply: "応募する", account: "応募内容はログイン中のアカウントで安全に管理されます。", closeError: "エラーメッセージを閉じる", loadError: "オーディション情報を読み込めませんでした。",
    total: (count) => `全${count}件`, emptyTitle: "まだ応募したオーディションはありません。", emptyDescription: "募集中のキャンペーンを選んで応募してください。", campaignFallback: "オーディション", applicationFallback: "応募書類", receipt: "受付番号", edit: "修正", campaign: "オーディションキャンペーン", selectCampaign: "キャンペーンを選択してください", noCampaign: "現在応募できるオーディションはありません。", noCampaignDescription: "新しい募集はこちらでお知らせします。", deadline: (date) => `${date} 締切`,
    status: { pending: "受付", reviewing: "審査中", accepted: "合格", rejected: "不合格" }, required: (label) => `${label}を入力してください。`, invalidEmail: (label) => `${label}の形式を確認してください。`, consent: (label) => `${label}への同意が必要です。`, tooLong: (label, max) => `${label}は${max}文字まで入力できます。`, fileTooLarge: (label) => `${label}のファイルサイズを確認してください。`,
    submitFailed: "送信できませんでした。入力内容を確認してください。", saved: "応募書類を受け付けました。", updated: "応募書類を更新しました。", viewMine: "応募履歴を確認", review: "送信前の確認", reviewNew: "以下の内容で応募書類を送信します。", reviewUpdate: "以下の内容で応募書類を更新します。", revise: "修正する", saving: "保存中…", saveUpdate: "変更を保存", finalSubmit: "応募する", select: "選択してください", replaceFile: "別のファイルに変更", chooseFile: "ファイルを選択", maxFile: (max) => `最大${max}MB`, existingFile: "登録済みファイル", removeFile: "ファイルを削除", reviewChanges: "変更内容を確認", reviewSubmission: "応募内容を確認",
    errors: { REQUIRED_FIELD_MISSING: "必須項目をすべて入力してください。", VALID_EMAIL_REQUIRED: "正しいメールアドレスを入力してください。", CONSENT_REQUIRED: "必須の同意項目を確認してください。", INVALID_OPTION: "選択項目を確認してください。", INVALID_DATE: "日付を確認してください。", ANSWER_TOO_LONG: "文字数制限を超えている項目があります。", INVALID_FILE_TYPE: "許可されていないファイル形式です。", FILE_TOO_LARGE: "添付ファイルのサイズを確認してください。", CAMPAIGN_CLOSED: "応募期間は終了しました。", ALREADY_SUBMITTED: "このキャンペーンにはすでに応募済みです。", RATE_LIMITED: "本日の送信回数上限に達しました。", UNAUTHORIZED: "ログインしてから応募してください。", SUBMISSION_NOT_FOUND: "更新する応募書類が見つかりません。", SERVICE_UNAVAILABLE: "送信サービスを一時的に利用できません。", SUBMISSION_FAILED: "応募書類を保存できませんでした。しばらくしてからもう一度お試しください。" },
  },
};
